export DROBO="5n"
export TOOLCHAIN="/usr/local/arm-2010.09"
export ARCH="armv7-a"
export PATH="${TOOLCHAIN}/bin:~/bin:$PATH"
export CFLAGS="-march=${ARCH} -mcpu=cortex-a9 -mfpu=vfpv3-d16 -mfloat-abi=softfp"
export CXXFLAGS="${CFLAGS}"
export CC="${TOOLCHAIN}/bin/arm-none-linux-gnueabi-gcc"
export CXX="${TOOLCHAIN}/bin/arm-none-linux-gnueabi-g++"
export AR="${TOOLCHAIN}/bin/arm-none-linux-gnueabi-ar"
export RANLIB="${TOOLCHAIN}/bin/arm-none-linux-gnueabi-ranlib"
export STRIP="${TOOLCHAIN}/bin/arm-none-linux-gnueabi-strip"
export DROBOAPPS="/mnt/DroboFS/Shares/DroboApps"
